[package]
name = "simple"
version = "0.0.43-alpha2"
authors = ["Ashanti Mutinta <Ashantimutinta@gmail.com>"]
edition = "2018"

[dependencies]
hdk = { path = "../../../../crates/hdk" }
hdk-proc-macros = { path = "../../../../crates/hdk_v2" }
serde = "=1.0.100"
serde_json = { version = "=1.0.47", features = ["preserve_order"] }
serde_derive = "=1.0.100"
holochain_json_derive = "=0.0.20"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
