[package]
name = "hc_dna"
version = "0.1.0"
authors = ["neonphog <neonphog@gmail.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
uuid = { version = "0.6.5", features = ["v4"] }
