[package]
name = "holochain_metrics"
version = "0.0.35-alpha7"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
edition = "2018"

[dependencies]
base64 = "=0.10.1"
shrinkwraprs = "=0.2.1"
serde = { version = "=1.0.89", features = ["rc"] }
serde_derive = "=1.0.89"
holochain_locksmith = { path = "../locksmith" }
chrono = "=0.4.6"
serde_json = { version = "=1.0.39", features = ["preserve_order"] }
snowflake = { version = "=1.3.0", features = ["serde_support"] }
bitflags = "=1.0.4"
failure = "=0.1.5"
futures-preview = "=0.3.0-alpha.17"
futures-core-preview = "=0.3.0-alpha.17"
futures-channel-preview = "=0.3.0-alpha.17"
futures-executor-preview = "=0.3.0-alpha.17"
futures-io-preview = "=0.3.0-alpha.17"
futures-sink-preview = "=0.3.0-alpha.17"
futures-util-preview = "=0.3.0-alpha.17"
lazy_static = "=1.2.0"
unwrap_to = "=0.1.0"
num-traits = "=0.2.6"
num-derive = "=0.2.4"
toml = "=0.5.0"
log = "=0.4.8"
holochain_logging = "=0.0.4"
boolinator = "=2.4.0"
jsonrpc-core = "14.0.1"
jsonrpc-lite = "=0.5.0"
globset = "=0.4.2"
pretty_assertions = "=0.6.1"
pin-utils = "=0.1.0-alpha.4"
clokwerk = "=0.1.0"
crossbeam-channel = "=0.3.8"
regex = "=1.1.2"
env_logger = "=0.6.1"
url = { version = "=2.1.0", features = ["serde"] }
rand = "0.7.2"
## For cloudwatch
rusoto_cloudwatch = "=0.41.0"
rusoto_logs = "=0.41.0"
rusoto_core = "=0.41.0"
##rusoto = { version="0.41.0", features= ["cloudwatch", "logs", "core"] }
## For descriptive statistics on metrics
streaming-stats = "=0.2.2"

[dev-dependencies]
tempfile = "=3.0.7"
