[book]
authors = ["Murray J Brown"]
multilingual = false
src = "src"
title = "FAQ"
description = "Frequently Asked Questions"

[build]
build-dir = "build"
create-missing = false
preprocess = ["links", "index"]

