[package]
name = "holochain_dpki"
version = "0.0.43-alpha2"
description = "holochain dpki"
license = "GPL-3.0-only"
homepage = "https://github.com/holochain/holochain-rust"
documentation = "https://github.com/holochain/holochain-rust"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
edition = "2018"

[dependencies]
lazy_static = "=1.4.0"
base64 = "=0.10.1"
holochain_core_types = { version = "=0.0.43-alpha2", path = "../core_types" }
holochain_tracing_macros = "=0.0.17"
newrelic="0.2"
lib3h_sodium = "=0.0.36"
holochain_persistence_api = "=0.0.15"
serde = "=1.0.100"
serde_derive = "=1.0.100"
serde_json = { version = "=1.0.47", features = ["preserve_order"] }
hcid = "=0.0.6"
bip39 = "=0.6.0-beta.1"
holochain_common = { version = "=0.0.43-alpha2", path = "../common" }
