# handy validation tool:
# https://ci.appveyor.com/tools/validate-yaml
environment:
 global:
  CHANNEL: nightly-2018-11-28

 matrix:
  - TARGET: x86_64-pc-windows-msvc

install:
 - ps: >-
     $Env:PATH += ';C:\msys64\usr\bin'
 - curl -sSf -o rustup-init.exe https://win.rustup.rs/
 - rustup-init.exe -y --default-host %TARGET% --default-toolchain %CHANNEL%
 - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
 - rustc -Vv
 - cargo -V

# Building is done in the test phase, so we disable Appveyor's build phase.
build: false
