# handy validation tool:
# https://ci.appveyor.com/tools/validate-yaml
# references
# https://crate-ci.github.io/pr/testing.html
# https://github.com/japaric/trust/blob/master/appveyor.yml

# needed for wabt-rs
# https://github.com/pepyakin/wabt-rs/blob/master/appveyor.yml#L1
os: Visual Studio 2017

# https://www.appveyor.com/blog/2014/06/04/shallow-clone-for-git-repositories/
shallow_clone: true

environment:
 global:
  RUST_VERSION: nightly-2018-11-28
  TARGET: x86_64-pc-windows-msvc
  WASM_TARGET: wasm32-unknown-unknown

 # as per rust docs
 # https://github.com/rust-lang/rust/blob/master/appveyor.yml#L12
 appveyor_build_worker_cloud: gce

install:
 # zmq
 - set PATH=%PATH%;%APPVEYOR_BUILD_FOLDER%\vendor\zmq\bin
 - set LIBZMQ_PREFIX=%APPVEYOR_BUILD_FOLDER%\vendor\zmq

 # rust
 - curl -sSf -o rustup-init.exe https://win.rustup.rs/
 - rustup-init.exe -y --default-host %TARGET% --default-toolchain %RUST_VERSION%
 - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
 - rustc -Vv
 - cargo -V
 - rustup target add %WASM_TARGET%

cache:
 # - C:\Users\appveyor\.rustup
 - C:\Users\appveyor\.cargo
 - C:\Users\appveyor\target

test_script:
 - cargo build --release --target %WASM_TARGET% --manifest-path core\src\nucleus\actions\wasm-test\Cargo.toml
 # - cargo build --release --target %WASM_TARGET% --manifest-path container_api\wasm-test\Cargo.toml
 # - cargo build --release --target %WASM_TARGET% --manifest-path hdk-rust\wasm-test\Cargo.toml
 # - cargo build --release --target %WASM_TARGET% --manifest-path wasm_utils\wasm-test\integration-test\Cargo.toml

 # - cargo test --all --exclude hc --release --target %TARGET% --target-dir %USERPROFILE%\target --manifest-path Cargo.toml

# Building is done in the test phase, so we disable Appveyor's build phase.
build: false
