# handy validation tool:
# https://ci.appveyor.com/tools/validate-yaml
# references
# https://github.com/japaric/trust/blob/master/appveyor.yml
environment:
 global:
  RUST_VERSION: nightly-2018-11-28
  WASM_TARGET: wasm32-unknown-unknown

 matrix:
  - TARGET: x86_64-pc-windows-msvc

install:
 - ps: >-
     $Env:PATH += ';C:\msys64\usr\bin'
 - curl -sSf -o rustup-init.exe https://win.rustup.rs/
 - rustup-init.exe -y --default-host %TARGET% --default-toolchain %RUST_VERSION%
 - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
 - rustc -Vv
 - cargo -V
 - rustup target add %WASM_TARGET%

cache:
 - C:\Users\appveyor\.rustup
 - C:\Users\appveyor\.cargo

 - .rustup
 - .cargo
 - target

 - core\src\nucleus\actions\wasm-test\.cargo
 - core\src\nucleus\actions\wasm-test\target

test_script:
 - set CARGO_HOME=core\src\nucleus\actions\wasm-test\.cargo
 - set CARGO_TARGET_DIR=core\src\nucleus\actions\wasm-test\target
 - cargo build --release --target %WASM_TARGET% --manifest-path core\src\nucleus\actions\wasm-test\Cargo.toml

 - set CARGO_HOME=container_api\wasm-test\.cargo
 - set CARGO_TARGET_DIR=container_api\wasm-test\target
 - cargo build --release --target %WASM_TARGET% --manifest-path container_api\wasm-test\Cargo.toml
 # - cargo build --manifest-path hdk-rust/wasm-test/Cargo.toml --release --target wasm32-unknown-unknown
 # - cargo build --manifest-path wasm_utils/wasm-test/integration-test/Cargo.toml --release --target wasm32-unknown-unknown

# Building is done in the test phase, so we disable Appveyor's build phase.
build: false
