language: rust
rust:
  - 1.26.2
cache: cargo
install:
  - rustup component add rustfmt-preview
  - rustup update nightly
  - cargo +nightly install clippy --force
  - cargo +nightly install cargo-tarpaulin --force
script:
  - make test
