language: rust
rust:
  - 1.26.2
cache: cargo
install:
  - rustup component add rustfmt-preview
script:
  - cargo build --verbose --all --features "strict"
  - cd hc_core/src/nucleus/wasm-test && cargo build --target wasm32-unknown-unknown
  - cargo test --verbose --all --features "strict"
  - cargo fmt -- --write-mode=diff
