services:
  - docker
dist: trusty
cache:
  directories:
    - docker_cache

before_install: |
  if [ -f docker_cache/cache.tar.gz ]; then
    gzip -dc docker_cache/cache.tar.gz | docker load
  fi

install:
  - docker pull sphinxc0re/holochain-rust:develop
  - mkdir -p docker_cache
  - docker save sphinxc0re/holochain-rust:develop | gzip > docker_cache/cache.tar.gz

script:
  . docker/run-test

after_success:
  - . docker/run-cov
  - bash <(curl -s https://codecov.io/bash)
