services:
  - docker
dist: trusty
cache:
  directories:
    - docker_cache

before_script:
  - gzip -dc docker_cache/cache.tar.gz | docker load

install:
  - docker pull sphinxc0re/holochain-rust:develop
  - mkdir docker_cache
  - docker save sphinxc0re/holochain-rust:develop | gzip > docker_cache/cache.tar.gz

script:
  . docker/run-test

after_success:
  - . docker/run-cov
  - bash <(curl -s https://codecov.io/bash)
