services:
  - docker

dist: trusty

jobs:
  include:
    - name: "C tests"
      install: docker pull holochain/holochain-rust:develop
      script:
        - . docker/run make build test_c_ci

    - name: "Standard tests + code coverage"
      cache: cargo
      install:
        - curl https://sh.rustup.rs -sSf | sh
        - make install_rust_wasm
        - make wasm_build
        - make install_tarpaulin
      script: make cov
      after_success:
        - bash <(curl -s https://codecov.io/bash)


    - name: "Formatting & clippy"
      install: docker pull holochain/holochain-rust:develop
      script:
        - . docker/run make fmt_check
        - . docker/run make clippy

    - name: "Mdbook Build"
      language: rust
      cache: cargo
      install: cargo install mdbook --vers "^0.1.0" || echo "Mdbook already installed"
      script: ./travis-update-book.sh
      env:
        - ENCRYPTION_LABEL: "30dd9296640e"
        - COMMIT_AUTHOR_EMAIL: "connor.turland@holo.host"
