language: rust
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - libssl-dev
cache: cargo
rust:
  - 1.26.2

install:
  - rustup component add rustfmt-preview
  - rustup update nightly
  - cargo +nightly install clippy --force
  - RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo +nightly install cargo-tarpaulin --force

script:
  - make test
