language: rust
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - libssl-dev
cache: cargo
# pinning versions/caching
# https://dev.to/cad97/great-rust-ci-1fk6
rust:
  - nightly-2018-06-01
env:
  - CLIPPY_VERSION=0.0.206
install:
  - rustup default nightly-2018-06-01
  - rustup update
  - rustup component add rustfmt-preview
  - cargo install clippy --version $CLIPPY_VERSION || echo "clippy already installed"
  - RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin || echo "tarpaulin already installed"
  - rustup target add wasm32-unknown-unknown
script:
  - make test
