language: rust
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - libssl-dev
cache: cargo
rust:
  - nightly

install:
  - rustup default nightly
  - rustup update
  - rustup component add rustfmt-preview
  - cargo install clippy --force
  - RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin --force

script:
  - make test
