dist: trusty

# https://docs.travis-ci.com/user/customizing-the-build/#safelisting-or-blocklisting-branches
# we build all PRs already, don't need redundant branch builds
branches:
  only:
    - master
    - develop

jobs:
  include:
    - name: "C tests"
      # manually cache as we manually install rustup
      # https://docs.travis-ci.com/user/caching/#rust-cargo-cache
      cache:
        directories:
          - $HOME/.cargo
          - $TRAVIS_BUILD_DIR/target
          - $TRAVIS_BUILD_DIR/core/src/nucleus/wasm-test/target
          - $TRAVIS_BUILD_DIR/core_api/wasm-test/commit/target
          - $TRAVIS_BUILD_DIR/core_api/wasm-test/round_trip/target
      install:
        - make install_rustup
        - export PATH=$HOME/.cargo/bin:$PATH
        - make install_rust_wasm
      script:
        - make wasm_build test_c_ci

    - name: "Standard tests + code coverage"
      # sudo is needed for codecov, which makes things 20-50s slower
      # https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system
      sudo: true
      # manually cache as we manually install rustup
      # https://docs.travis-ci.com/user/caching/#rust-cargo-cache
      cache:
        directories:
          - $HOME/.cargo
          - $TRAVIS_BUILD_DIR/target
          - $TRAVIS_BUILD_DIR/core/src/nucleus/wasm-test/target
          - $TRAVIS_BUILD_DIR/core_api/wasm-test/commit/target
          - $TRAVIS_BUILD_DIR/core_api/wasm-test/round_trip/target
      install:
        - make install_rustup
        - export PATH=$HOME/.cargo/bin:$PATH
        - make install_rust_wasm
        - make install_tarpaulin
      script: make wasm_build cov
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - name: "Formatting & clippy"
      # manually cache as we manually install rustup
      # https://docs.travis-ci.com/user/caching/#rust-cargo-cache
      cache:
        directories:
          - $HOME/.cargo
          - $TRAVIS_BUILD_DIR/target
      install:
        - make install_rustup
        - export PATH=$HOME/.cargo/bin:$PATH
        - make install_rust_tools
      script:
        - make fmt_check
        - make clippy

    - name: "Mdbook Build"
      # manually cache as we manually install rustup
      # https://docs.travis-ci.com/user/caching/#rust-cargo-cache
      cache:
        directories:
          - $HOME/.cargo
          - $TRAVIS_BUILD_DIR/target
      install:
        - make install_rustup
        - export PATH=$HOME/.cargo/bin:$PATH
        - make install_mdbook
      script: ./travis-update-book.sh
      env:
        - ENCRYPTION_LABEL: "30dd9296640e"
        - COMMIT_AUTHOR_EMAIL: "connor.turland@holo.host"
