# https://docs.travis-ci.com/user/customizing-the-build/#safelisting-or-blocklisting-branches
# we build all PRs already, don't need redundant branch builds
branches:
  only:
    - master
    - develop

jobs:
  include:
    - name: "windows build & test all"
      os: windows
      env:
        - LIBZMQ_PREFIX=C:\\Users\\travis\\build\\holochain\\holochain-rust\\vendor\\zmq
      language: rust
      rust: nightly-2018-10-12-x86_64-pc-windows-msvc
      before_install:
        - choco install python2
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
      install:
        - rustup target add wasm32-unknown-unknown --toolchain nightly-2018-10-12-x86_64-pc-windows-msvc
      script:
        - PATH=$PATH:/c/Users/travis/build/holochain/holochain-rust/vendor/zmq/bin
        # Build WASMs
        - cargo +nightly-2018-10-12-x86_64-pc-windows-msvc build --manifest-path core/src/nucleus/wasm-test/Cargo.toml --release --target wasm32-unknown-unknown
        - cargo +nightly-2018-10-12-x86_64-pc-windows-msvc build --manifest-path core/src/nucleus/actions/wasm-test/Cargo.toml --release --target wasm32-unknown-unknown
        - cargo +nightly-2018-10-12-x86_64-pc-windows-msvc build --manifest-path container_api/wasm-test/round_trip/Cargo.toml --release --target wasm32-unknown-unknown
        - cargo +nightly-2018-10-12-x86_64-pc-windows-msvc build --manifest-path container_api/wasm-test/commit/Cargo.toml --release --target wasm32-unknown-unknown
        - cargo +nightly-2018-10-12-x86_64-pc-windows-msvc build --manifest-path hdk-rust/wasm-test/Cargo.toml --release --target wasm32-unknown-unknown
        - cargo +nightly-2018-10-12-x86_64-pc-windows-msvc build --manifest-path wasm_utils/wasm-test/integration-test/Cargo.toml --release --target wasm32-unknown-unknown
        # Build & test All
        - cargo +nightly-2018-10-12-x86_64-pc-windows-msvc test --all

    - name: "C binding tests"
      dist: trusty
      # https://github.com/travis-ci/travis-ci/issues/5175#issuecomment-215016943
      language: bash

      # sudo is needed for codecov, && system library install which makes things 20-50s slower
      # https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system
      sudo: true

      # manually cache as we manually install rustup
      # https://docs.travis-ci.com/user/caching/#rust-cargo-cache
      cache:
        timeout: 1000
        directories:
          - $HOME/.cargo
          # faster to build this than manage a cache for the target
          # - $TRAVIS_BUILD_DIR/target
      install:
        - export PATH=$HOME/.cargo/bin:$PATH
      script:
        - make test_c_ci
      before_cache:
        - rm -rf $HOME/.cargo/registry/index

    - name: "Standard tests + code coverage"
      dist: trusty
      language: node_js
      node_js:
        - "8"

      # sudo is needed for codecov, && system library install which makes things 20-50s slower
      # https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system
      sudo: true

      # manually cache as we manually install rustup
      # https://docs.travis-ci.com/user/caching/#rust-cargo-cache
      cache:
        timeout: 1000
        directories:
          - $HOME/.cargo
          - $TRAVIS_BUILD_DIR/target
      install:
        - export PATH=$HOME/.cargo/bin:$PATH
      script: make code_coverage
      after_success:
        - bash <(curl -s https://codecov.io/bash)
      before_cache:
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/holochain*
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/holochain*/
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/libholochain*
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/libholochain*/
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/.fingerprint/holochain*/
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/.fingerprint/test_utils*/
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/incremental/holochain*/
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/incremental/test_utils*/
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/deps/holochain*
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/deps/libholochain*
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/deps/libtest_utils*
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/deps/test_utils*
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/libtest_utils*
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/test_utils*
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/incremental/echo_ipc_test*
        - rm -rf $TRAVIS_BUILD_DIR/target/.rustc_info.json
        - rm -rf $HOME/.cargo/registry/index

    - name: "Formatting & clippy"
      dist: trusty
      # https://github.com/travis-ci/travis-ci/issues/5175#issuecomment-215016943
      language: bash

      # sudo is needed for codecov, && system library install which makes things 20-50s slower
      # https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system
      sudo: true

      # manually cache as we manually install rustup
      # https://docs.travis-ci.com/user/caching/#rust-cargo-cache
      cache:
        timeout: 1000
        directories:
          - $HOME/.cargo
          - $TRAVIS_BUILD_DIR/target
      install:
        - export PATH=$HOME/.cargo/bin:$PATH
      script:
        - make fmt_check
        # @see #431
        # - make clippy
      before_cache:
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/holochain*
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/holochain*/
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/libholochain*
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/libholochain*/
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/.fingerprint/holochain*/
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/.fingerprint/test_utils*/
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/incremental/holochain*/
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/incremental/test_utils*/
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/deps/holochain*
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/deps/libholochain*
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/deps/libtest_utils*
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/deps/test_utils*
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/libtest_utils*
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/test_utils*
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/incremental/echo_ipc_test*
        - rm -rf $TRAVIS_BUILD_DIR/target/.rustc_info.json
        - rm -rf $HOME/.cargo/registry/index
