services:
  - docker
dist: trusty
cache: docker
install:
  docker pull sphinxc0re/holochain-rust:develop
script:
  . docker/run-test
after_success:
  - . docker/run-cov
  - bash <(curl -s https://codecov.io/bash)
