language: rust

cache: cargo

services:
  - docker

dist: trusty

install:
  - docker pull holochain/holochain-rust:develop

script:
  . docker/run-test

after_success:
  - . docker/run-cov
  - bash <(curl -s https://codecov.io/bash)
