services:
  - docker

dist: trusty

jobs:
  include:
    - name: "Standard tests"
      install: docker pull holochain/holochain-rust:develop
      script: . docker/run-test
    - name: "Code coverage"
      install: docker pull holochain/holochain-rust:develop
      script: . docker/run-cov
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - name: "Mdbook Build"
      language: rust
      cache: cargo
      install: cargo install mdbook --vers "^0.1.0" || echo "Mdbook already installed"
      script: ./travis-update-book.sh
      env:
        - ENCRYPTION_LABEL: "30dd9296640e"
        - COMMIT_AUTHOR_EMAIL: "connor.turland@holo.host"
