language: rust
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - libssl-dev
cache: cargo
# pinning versions/caching
# https://dev.to/cad97/great-rust-ci-1fk6
rust:
  - nightly-2018-06-01
env:
  global:
    - CLIPPY_VERSION=0.0.206
    - secure: R2/THCRt0p/5XR7vcYg77fNk2vLuBGcNIfu7/a47BxVREYUkAqHK2MpG6x9TbbUPnJksEpXeXHH3OVVyK7Q+QsNX6dcOfl15DBafJHlMbfMTJWGDm+pBhNLFSKtA3DRnyOTR/ZpN+xnN7A0TSl/WB+PNxX4TjZtFTAaVtZpVbK6Ins6pHylVh00biLVyZ/W2AowCqiM95Yt4SfnybHn8KApJ/orjbtlJL1+2qQa+rF5N625/pDDf4MF/CLbdODlKPJ1M704/Kq3mo4KgutL0xFPxI3hDPO6LwWdW/izmcfEP56J3UpuXbcnDwSgS6ieAH7gDjBZGC/BYp7IoZrvjLCUuL6QSefWm1G/NJZuL2J1PInHF8kKnvm6/bFkAcRNByVSsdrgqwjQUkHZ/1FP+OMEDFWZk1bRXt8nHsIa0VbmyM+7cn5sCgCIIEsBJbbyQA40eGk0BkCWBbqCrb1shSEYvYBM44CBZHuMIvpp0BfX9Fl5gM1XW0FfzUXw5lBmi6/JWy7DDAL0axkmFe3abq7vmWHUQybEW295UuUDvDO8ioTGYMWf5LLKs02nxIZIuccEdozlO1vohkucYpKamjZu/YcR0den7eHMxzU/dmTK8qZjKhQ6aOH/1xLpeCSE2fG5sHVT+0uQe/4p2Bq4QbF/ljk6kujUc4jlK6NIwg/g=
    - secure: KU/2msclYm1J9KQidXgRl63uEYev7op/kr5w37KNJaCTqmYUHk/090+4SQmEFf0csHNCeyqmHD4tTHQ4oKsIsmfmuC4EQkEmBvwBbQVT9+lmWM1cuHRZRnSudDa4UT36OVLc+iyR2wkTYcaDan6ZaYmd9tDW8pfyOP7TxH3rf/9TqACnKKjMeHyINxgijTqiSGNnBQaNyTiBa/y/60Eg78eqq3zVPZKkae6dqAJtHqrFJTLbE4rlfHcrkmYsZhUIcyXAzw/+elz4gKC4llPXQ9mpxruBJxI+LVOoFmaqTdXpYa/Bsc9PteJOQQdecPWS0XkbV6T7Y44gAtlevsbyedSv0tmVniM4jXTnsMJ0f3gZzV5kXLM2A5rpw3gIkdqtg+a3GkVIy229Ljz1KH17o6nf1AAndqrh7wCOMXTHt1xxC+26vExnAIcyDQHpzx/Y4vmGUAhJJujIfh9Ld4YYdI2r9dP3i8N8qxFZyuQ9Lh3S1AMdIf5sBRTr6rPnZtU0UC5HYWxlGhfv7eWuMydUX2zLOmgHQXkY9/Jp+4YJ3H/Ge1qf8UtfhZBxMJM6sYdplNVpNE6NE1CemprPc7A2AotUdGlUFdGGuxLSat8tPlLe0wlf31EhdskSOf35fUJuVSJDxb4x4Flan0O42qKAgjRT+OVYB4R9/8MWQi/k8+Y=
install:
  - rustup default nightly-2018-06-01
  - rustup update
  - rustup component add rustfmt-preview
  - cargo install clippy --version $CLIPPY_VERSION || echo "clippy already installed"
  - RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin || echo "tarpaulin already installed"
  - rustup target add wasm32-unknown-unknown
script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - . docker/build-ubuntu
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push holochain/rust-ubuntu
