dist: trusty

# https://docs.travis-ci.com/user/customizing-the-build/#safelisting-or-blocklisting-branches
# we build all PRs already, don't need redundant branch builds
branches:
  only:
    - master
    - develop

jobs:
  include:
    - name: "C binding tests"
      # manually cache as we manually install rustup
      # https://docs.travis-ci.com/user/caching/#rust-cargo-cache
      cache:
        timeout: 1000
        directories:
          - $HOME/.cargo
          # - $TRAVIS_BUILD_DIR/target
      install:
        - make install_rustup
        - export PATH=$HOME/.cargo/bin:$PATH
        - make install_rust_wasm
      script:
        - make test_c_ci
      # faster to build this than have it invalidate the cache every build
      # before_cache:
      #   - rm -rf $TRAVIS_BUILD_DIR/target/debug/holochain*/
      #   - rm -rf $TRAVIS_BUILD_DIR/target/debug/libholochain*/
      #   - rm -rf $TRAVIS_BUILD_DIR/target/debug/.fingerprint/holochain*/
      #   - rm -rf $TRAVIS_BUILD_DIR/target/debug/.fingerprint/test_utils*/
      #   - rm -rf $TRAVIS_BUILD_DIR/target/debug/incremental/holochain*/
      #   - rm -rf $TRAVIS_BUILD_DIR/target/debug/incremental/test_utils*/
      #   - rm -rf $TRAVIS_BUILD_DIR/target/.rustc_info.json

    - name: "Standard tests + code coverage"
      # sudo is needed for codecov, which makes things 20-50s slower
      # https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system
      sudo: true
      # manually cache as we manually install rustup
      # https://docs.travis-ci.com/user/caching/#rust-cargo-cache
      cache:
        timeout: 1000
        directories:
          - $HOME/.cargo
          - $TRAVIS_BUILD_DIR/target
      install:
        - make install_rustup
        - export PATH=$HOME/.cargo/bin:$PATH
        - make install_rust_wasm
        - make install_tarpaulin
      script: make cov
      after_success:
        - bash <(curl -s https://codecov.io/bash)
      before_cache:
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/holochain*/
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/libholochain*/
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/.fingerprint/holochain*/
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/.fingerprint/test_utils*/
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/incremental/holochain*/
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/incremental/test_utils*/
        - rm -rf $TRAVIS_BUILD_DIR/target/.rustc_info.json

    - name: "Formatting & clippy"
      # manually cache as we manually install rustup
      # https://docs.travis-ci.com/user/caching/#rust-cargo-cache
      cache:
        timeout: 1000
        directories:
          - $HOME/.cargo
          - $TRAVIS_BUILD_DIR/target
      install:
        - make install_rustup
        - export PATH=$HOME/.cargo/bin:$PATH
        - make install_rust_tools
      script:
        - make fmt_check
        - make clippy
      before_cache:
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/holochain*/
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/libholochain*/
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/.fingerprint/holochain*/
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/.fingerprint/test_utils*/
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/incremental/holochain*/
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/incremental/test_utils*/
        - rm -rf $TRAVIS_BUILD_DIR/target/.rustc_info.json

    - name: "Mdbook Build"
      env:
        - ENCRYPTION_LABEL: "30dd9296640e"
        - COMMIT_AUTHOR_EMAIL: "connor.turland@holo.host"
      # manually cache as we manually install rustup
      # https://docs.travis-ci.com/user/caching/#rust-cargo-cache
      cache:
        timeout: 1000
        directories:
          - $HOME/.cargo
          - $TRAVIS_BUILD_DIR/target
      install:
        - make install_rustup
        - export PATH=$HOME/.cargo/bin:$PATH
        - make install_mdbook
      script: ./travis-update-book.sh
      before_cache:
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/holochain*/
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/libholochain*/
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/.fingerprint/holochain*/
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/.fingerprint/test_utils*/
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/incremental/holochain*/
        - rm -rf $TRAVIS_BUILD_DIR/target/debug/incremental/test_utils*/
        - rm -rf $TRAVIS_BUILD_DIR/target/.rustc_info.json
