language: rust
sudo: required
services:
- docker
dist: trusty
addons:
  apt:
    packages:
    - libssl-dev
cache: cargo
rust:
- nightly-2018-06-01
env:
  global:
  - CLIPPY_VERSION=0.0.206
  - secure: iqQbi+VfXWtlBUc/rfppOp0vb0KwfwJCyF3Nrcv8i7m2aNwAUujK/5rgerCjvpAswjGCeb0HG3Qkwqg1NA7sVfbk4qEkuMx/d5xh92SRF8m1n2eZmu3/d2xsP9t3Fsa1vRNHLu1OVP1TqeHBAbKAFhCN2t4BFRvWTerr3fVIK1s7bEJQ5vXI7mBr5ARASHpt+Z6dvU/ddKybRk7mX5pAUvoTXct4V5owjZV9WfQYlxZe1jn4vEwYvdGva2kzbgYp23eY3pCiR9asAt9JSYGE2Maoa9GzmVrbKdtOkbRlnxB6/uF2yA3NLcmTWsH+2iFNy3r46CKYB3cUKJM2iNeMY7Udkqz0ATigNGhtBTAGjgadVv2+aRz3pttgruJNxIq0hofbWIsUSJ/Tcs1EVAVPl1k8uIKA0bJrkvK6BKLco0Ehcknj36eiYA48ztQUAdeCIWqezx7FMI3u4ulEqPjG4pjRWkWtcra4aYyYr3aRnPFY6HZFcW9vQ/kucHK69zHZ1D/7aoUuCgx3SaH8bQyKhzekclkSvN24veOLf02hBXL7SkCDx6rImdrYYxUWgaYkYNojgBeW3VxEnQlKvUHst3545ufwoYZA92+NyUrN/w+louZ6vV9/F2FAhidMN2OPAMvfVk1YRHY/bNYRPsIOHUxHFBGlNtStCpCvUhbGQdE=
  - secure: etR1iDaJ7xaMD33xNu4ctdf/exByMFRF0ndwZ5bL9FZj9NfAzYr2qQYQn636Rll0r7JzMKrmK7ZdPh3Oi/8UHEh7COQPx5U1bfOZEzE0sY9ik9me020LFAy+zww4PZRKs1Sb85iL4mclKhhdwE4Vj5ilkGD5MNXGP11ta15UCqIfbD3US8KHChSTPJlFwgC400nYZpCalZG4jrrYDc73qjhgoNlmpugbch8qKXcBTMkp+ZxMICIOYGQ9qJXiWU+m3ohxmykNf2ZbMM3qTVtk0VcyJAa6NBCfsut8GWIPjs/DhdxfQYgNraxFVMtDgxmnX4x1mwIvlSM7GstuMV8SVCto1S/ZU92lmYrfJQ+k/47H3rUez6K5HZVHXbf9Q+yO5WoGs1ObJbEtrf4T8feQhCYcoCWIfFsCWwS0o6PVfLRJQnDT5n5o2xWsNthxa+QzPcn4uBsKGIZ0/Oy2B/7IeKCrleJFddHJ4ebyy8Me2SMw2muyXg8bEjibilEOz5ZiDX2H8mSD2VAk5/VMhvqDbsMHZ66ICXQx7c0g39Lx33l13CFS3apEltVVft4hOxxpC/d2LF2XwDQgp5Q0XchZIazZmVZAmZrXn6nsv0fVjvT6URMtThNfHxeu1WRawzx7eEL4hlKtpwXiMX6FKo2vv3UX3pb16YNELGigRRSygg0=
install:
- rustup default nightly-2018-06-01
- rustup update
- rustup component add rustfmt-preview
- cargo install clippy --version $CLIPPY_VERSION || echo "clippy already installed"
- RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin || echo
  "tarpaulin already installed"
- rustup target add wasm32-unknown-unknown
script:
- make test
after_success:
- bash <(curl -s https://codecov.io/bash)
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
  docker build -f docker/Dockerfile.ubuntu -t holochain/rust-ubuntu "$@" .; cd ..;
  fi
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
  docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"; docker push holochain/rust-ubuntu;
  fi
- if [ "$TRAVIS_BRANCH" == "develop" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
  docker build -f docker/Dockerfile.ubuntu -t holochain/rust-ubuntu:develop "$@" .;
  cd ..; fi
- if [ "$TRAVIS_BRANCH" == "develop" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
  docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"; docker push holochain/rust-ubuntu:develop;
  fi
