services:
  - docker

dist: trusty

jobs:
  include:
    - name: "Non C binding tests"
      install: docker pull holochain/holochain-rust:develop
      script: . docker/run make test_non_c
    - name: "C binding tests"
      install: docker pull holochain/holochain-rust:develop
      script: . docker/run make c_binding_tests
    - name: "Tests"
      install: docker pull holochain/holochain-rust:develop
      script: . docker/run-test
      after_success:
        - . docker/run-cov
        - bash <(curl -s https://codecov.io/bash)
    - name: "Mdbook Build"
      language: rust
      cache: cargo
      install: cargo install mdbook --vers "^0.1.0" || echo "Mdbook already installed"
      script: ./travis-update-book.sh
      env:
        - ENCRYPTION_LABEL: "30dd9296640e"
        - COMMIT_AUTHOR_EMAIL: "connor.turland@holo.host"
