language: rust
rust:
  - 1.26.2
cache: cargo
install:
  - rustup component add rustfmt-preview
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo fmt -- --write-mode=diff
