language: rust
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - libssl-dev
cache: cargo
# pinning versions/caching
# https://dev.to/cad97/great-rust-ci-1fk6
rust:
  - nightly-2018-06-20
env:
  - CLIPPY_VERSION=0.0.179
install:
  - rustup default nightly-2018-06-20
  - rustup update
  - rustup component add rustfmt-preview
  - cargo install clippy --version $CLIPPY_VERSION || echo "clippy already installed"
  - RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin --force

script:
  - make test
