language: rust

cache: cargo

services:
  - docker

dist: trusty

install:
  - docker pull holochain/holochain-rust:develop

script:
  - . docker/run-test

env:
  global:
  - ENCRYPTION_LABEL: "<.... replace with encryption label ....>"
  - COMMIT_AUTHOR_EMAIL: "connor.turland@holo.host"

after_success:
  - . docker/run-cov
  - bash <(curl -s https://codecov.io/bash)
  - bash ./travis-update-book.sh
