# https://www.appveyor.com/docs/enterprise/running-builds-on-aws/

build_cloud: master
image: hc-test

shallow_clone: true
version: 1.0.{build}
build: false
max_jobs: 20

environment:
 global:
  APPVEYOR_BUILD_WORKER_CLOUD: master

test_script:
 - setx RUSTFLAGS -D warnings -Z external-macro-backtrace -Z thinlto -C codegen-units=32 -C opt-level=z
 - cargo test --release -p hc --target-dir C:\build\cli\target