# https://www.appveyor.com/docs/enterprise/running-builds-on-aws/

build_cloud: master
image: build-0.0.4

shallow_clone: true
version: 1.0.{build}
build: false
max_jobs: 20

environment:
 global:
  APPVEYOR_BUILD_WORKER_CLOUD: master

test_script:
 - pwd       
 - cargo  test --release
