# https://www.appveyor.com/docs/enterprise/running-builds-on-aws/

build_cloud: master
image: foo

shallow_clone: true
version: 1.0.{build}
build: false

environment:
 global:
  APPVEYOR_BUILD_WORKER_CLOUD: master
  RUST_VERSION: nightly-2019-01-24
  TARGET: x86_64-pc-windows-msvc
  WASM_TARGET: wasm32-unknown-unknown

test_script:
 - cargo build --all --exclude holochain_node
