# https://www.appveyor.com/docs/enterprise/running-builds-on-aws/

build_cloud: master
image: hc-test

shallow_clone: true
version: 1.0.{build}
build: false
max_jobs: 20

environment:
 global:
  APPVEYOR_BUILD_WORKER_CLOUD: master

test_script:
 - setx %hc_target_prefix% C:\build\
 - setx test_p hc
 - setx test_path cli\
 - cargo test --release -p %test_p% --target-dir %hc_target_prefix%%test_path%target
