# https://www.appveyor.com/docs/enterprise/running-builds-on-aws/

build_cloud: master
image: foo

shallow_clone: true
version: 1.0.{build}
build: false

environment:
 global:
  APPVEYOR_BUILD_WORKER_CLOUD: master
  RUST_VERSION: nightly-2019-01-24
  TARGET: x86_64-pc-windows-msvc
  WASM_TARGET: wasm32-unknown-unknown

 matrix:
  - TEST_P: holochain_cas_implementations
    TEST_PATH: cas_implementations

  - TEST_P: hc
    TEST_PATH: hc

test_script:
 - cargo test --release -p %TEST_P% --target-dir %TEST_PATH%\target
