# https://www.appveyor.com/docs/enterprise/running-builds-on-aws/

build_cloud: master
image: foo

shallow_clone: true
version: 1.0.{build}
build: false

environment:
 global:
  APPVEYOR_BUILD_WORKER_CLOUD: master

test_script:
 # - setx path %PATH%;...
 - cargo build --all --exclude holochain_node
