# https://www.appveyor.com/docs/enterprise/running-builds-on-aws/

build_cloud: master
image: hc-test

shallow_clone: true
version: 1.0.{build}
build: false
max_jobs: 20

environment:
 global:
  APPVEYOR_BUILD_WORKER_CLOUD: master

test_script:
  - cargo test --release -p "holochain_cas_implementations" --target-dir "C:\build\cas_implementations\target"
  - cargo test --release -p "holochain_dna_c_binding" --target-dir "C:\build\dna_c_binding\target"
  - cargo test --release -p "holochain_sodium" --target-dir "C:\build\sodium\target"
  - cargo test --release -p "hc" --target-dir "C:\build\cli\target"
  - cargo test --release -p "holochain_core_types" --target-dir "C:\build\core_types\target"
  - cargo test --release -p "holochain_net" --target-dir "C:\build\net\target"

  - cargo build --manifest-path "wasm_utils\wasm-test\integration-test\Cargo.toml" --release --target wasm32-unknown-unknown --target-dir "C:\build\wasm_utils\wasm-test\integration-test\target"
  - cargo test --release -p "holochain_wasm_utils" --target-dir "C:\build\holochain_wasm_utils\target"


  - cargo build --manifest-path "hdk-rust\wasm-test\Cargo.toml" --release --target wasm32-unknown-unknown --target-dir "C:\build\hdk-rust\wasm_utils\target"
  - cargo test --release -p "hdk" --target-dir "C:\build\hdk\target"


  - cargo build --manifest-path "conductor_api\wasm-test\Cargo.toml" --release --target wasm32-unknown-unknown --target-dir "C:\build\conductor_api\wasm-test\target"
  - cargo build --manifest-path "conductor_api\test-bridge-caller\Cargo.toml" --release --target wasm32-unknown-unknown --target-dir "C:\build\conductor_api\test-bridge-caller\target"
  - cargo test --release -p "holochain_conductor_api" --target-dir "C:\build\holochain_conductor_api\target"

 # @see https://ci.appveyor.com/project/thedavidmeister/holochain-rust/builds/23357334
 # - SET "test_p=holochain_net"
 # - SET "test_path=net\"
 # - SET "wasm_path="
 # - SET "wasm_path_2="
 # - scripts\windows\do-ci-test.bat

#  - SET "test_p=holochain_wasm_utils"
#  - SET "test_path=wasm_utils\"
#  - SET "wasm_path=wasm-test\integration-test\"
#  - SET "wasm_path_2="
#  - scripts\windows\do-ci-test.bat

#  - SET "test_p=hdk"
#  - SET "test_path=hdk-rust\"
#  - SET "wasm_path=wasm-test\"
#  - SET "wasm_path_2="
#  - scripts\windows\do-ci-test.bat

 # @see https://ci.appveyor.com/project/thedavidmeister/holochain-rust/builds/23357334
 # - SET "test_p=holochain_core"
 # - SET "test_path=core\"
 # - SET "wasm_path=src\nucleus\actions\wasm-test"
 # - SET "wasm_path_2="
 # - scripts\windows\do-ci-test.bat

#  - SET "test_p=holochain_conductor_api"
#  - SET "test_path=conductor_api\"
#  - SET "wasm_path=wasm-test\"
#  - SET "wasm_path_2=test-bridge-caller\"
#  - scripts\windows\do-ci-test.bat
