# https://www.appveyor.com/docs/enterprise/running-builds-on-aws/

build_cloud: master
image: hc-test

shallow_clone: true
version: 1.0.{build}
build: false
max_jobs: 20

environment:
 global:
  APPVEYOR_BUILD_WORKER_CLOUD: master

test_script:
 - $env:hc_target_prefix=C:\build\
 - $env:test_p=hc
 - $env:test_path=cli\
 - echo $env:test_p
 - echo $env:test_path
 - echo $env:hc_target_prefix
 - cargo test --release -p $env:test_p --target-dir $env:hc_target_prefix$env_test_pathtarget

 # - setx test_p hdk
 # - setx test_path hdk-rust\
 # - setx wasm_path wasm-test\
 # - cargo build --manifest-path %TEST_PATH%%WASM_PATH%Cargo.toml --release --target wasm32-unknown-unknown --target-dir %HC_TARGET_PREFIX%%TEST_PATH%%WASM_PATH%target
 # - cargo test --release -p %TEST_P% --target-dir %HC_TARGET_PREFIX%%TEST_PATH%target
