# https://www.appveyor.com/docs/enterprise/running-builds-on-aws/

build_cloud: master
image: hc-test

shallow_clone: true
version: 1.0.{build}
build: false
max_jobs: 20

environment:
 global:
  APPVEYOR_BUILD_WORKER_CLOUD: master

test_script:
 - rustup target add wasm32-unknown-unknown
 - SET hc_target_prefix=C:\build\

 - SET "test_p=hdk"
 - SET "test_path=hdk-rust\"
 - SET "wasm_path=wasm-test\"
 - SET "wasm_path_2="
 - scripts\windows\do-ci-test.bat

 - SET "test_p=holochain_wasm_utils"
 - SET "test_path=wasm_utils\"
 - SET "wasm_path=wasm-test\integration-test\"
 - SET "wasm_path_2="
 - scripts\windows\do-ci-test.bat

 - SET "test_p=holochain_conductor_api"
 - SET "test_path=conductor_api\"
 - SET "wasm_path=wasm-test\"
 - SET "wasm_path_2=test-bridge-caller\"
 - scripts\windows\do-ci-test.bat

 - SET "test_p=holochain_core"
 - SET "test_path=core\"
 - SET "wasm_path=src\nucleus\actions\wasm-test"
 - SET "wasm_path_2="
 - scripts\windows\do-ci-test.bat

 - SET "test_p=holochain_cas_implementations"
 - SET "test_path=cas_implementations\"
 - SET "wasm_path="
 - SET "wasm_path_2="
 - scripts\windows\do-ci-test.bat

 - SET "test_p=holochain_dna_c_binding"
 - SET "test_path=dna_c_binding\"
 - SET "wasm_path="
 - SET "wasm_path_2="
 - scripts\windows\do-ci-test.bat

 - SET "test_p=holochain_sodium"
 - SET "test_path=sodium\"
 - SET "wasm_path="
 - SET "wasm_path_2="
 - scripts\windows\do-ci-test.bat

 - SET "test_p=hc"
 - SET "test_path=cli\"
 - SET "wasm_path="
 - SET "wasm_path_2="
 - scripts\windows\do-ci-test.bat

 - SET "test_p=holochain_core_types"
 - SET "test_path=core_types\"
 - SET "wasm_path="
 - SET "wasm_path_2="
 - scripts\windows\do-ci-test.bat

 - SET "test_p=holochain_net"
 - SET "test_path=net\"
 - SET "wasm_path="
 - SET "wasm_path_2="
 - scripts\windows\do-ci-test.bat
