[workspace]

members = [
  "cli",
  "common",
  "conductor",
  "conductor_api",
  "core_api_c_binding",
  "core",
  "dna_c_binding",
  "hdk-rust",
  "net",
  "nodejs_waiter",
  "sodium",
  "dpki",
  "test_bin",
  "benchmarks"
]
exclude = [
  "test_utils",
  "app_spec",
  "nodejs_conductor/native",
]

[patch.crates-io]
openssl-sys = { git = "https://github.com/thedavidmeister/rust-openssl.git", rev = "e7a54f68d86684c82d2a796ed8f71884b88f5796" }
openssl-src = { git = "https://github.com/thedavidmeister/openssl-src-rs.git", rev = "77b4fa0b5ab83ee3593fc1d2998dc76cb64d9f6f" }
# openssl-sys = { git = "https://github.com/thedavidmeister/rust-openssl.git", branch = "v0.9.43-vendored" }
