[workspace]

members = [
  "cmd",
  "container",
  "container_api",
  "core_api_c_binding",
  "core",
  "dna_c_binding",
  "hdk-rust",
  "net",
  "net_connection",
  "net_ipc",
  "test_bin",
  "app_spec/zomes/blog/code",
]
exclude = [
  "test_utils",
  "app_spec",
  "nodejs_container/native",
]
