[workspace]

members = [
  "crates/cli",
  "common",
  "crates/holochain",
  "crates/conductor_lib",
  "crates/conductor_api",
  "crates/holochain_wasm",
  "crates/core",
  "crates/dpki",
  "crates/hdk_v2",
  "crates/hdk",
  "crates/net",
  "crates/sim2h",
  "crates/sim2h_server",
]
exclude = [
  "test_utils",
  "app_spec",
  "app_spec_proc_macro",
  "nodejs_conductor/native",
]

[patch.crates-io]
lib3h = { path = "/home/neonphog/projects/lib3h/crates/lib3h" }
lib3h_protocol = { path = "/home/neonphog/projects/lib3h/crates/lib3h_protocol" }
lib3h_crypto_api = { path = "/home/neonphog/projects/lib3h/crates/crypto_api" }
lib3h_sodium = { path = "/home/neonphog/projects/lib3h/crates/sodium" }
lib3h_zombie_actor = { path = "/home/neonphog/projects/lib3h/crates/zombie_actor" }
