[workspace]

members = [
  "crates/cli",
  "common",
  "crates/holochain",
  "crates/conductor_lib",
  "crates/conductor_api",
  "crates/holochain_wasm",
  "crates/core",
  "crates/dpki",
  "crates/hdk_v2",
  "crates/hdk",
  "crates/net",
  "crates/sim2h",
  "crates/sim2h_server",
]
exclude = [
  "test_utils",
  "app_spec",
  "app_spec_proc_macro",
  "nodejs_conductor/native",
]

[patch.crates-io]
lib3h = { git = "https://github.com/holochain/lib3h", branch = "ghost-mutex" }
lib3h_protocol = { git = "https://github.com/holochain/lib3h", branch = "ghost-mutex" }
lib3h_crypto_api = { git = "https://github.com/holochain/lib3h", branch = "ghost-mutex" }
lib3h_sodium = { git = "https://github.com/holochain/lib3h", branch = "ghost-mutex" }
lib3h_zombie_actor = { git = "https://github.com/holochain/lib3h", branch = "ghost-mutex" }
