[workspace]

members = [
  "cmd",
  "container",
  "container_api",
  "core_api_c_binding",
  "core",
  "dna_c_binding",
  "hdk-rust",
  "net",
  "net_connection",
  "net_ipc",
  "sodium",
  "test_bin",
]
exclude = [
  "test_utils",
  "app_spec",
  "nodejs_container/native",
  "rust_sodium-sys",
  "rust_zmq-sys",
]

[patch.crates-io]
rust_sodium-sys = { path = "./rust_sodium-sys" }
