[workspace]

members = [
  "container",
  "container_api",
  "core_api_c_binding",
  "core",
  "dna_c_binding",
  "hdk-rust",
  "net",
  "net_connection",
  "net_ipc",
  "test_bin",
]
exclude = ["test_utils"]
