# Repository Yaml
codecov:
  token: 684bc22e-c6ca-4ac5-b5be-d1dd250a4567
coverage:
  round: up
  range: 70..100
  status:
    project:
      default:
        target: 70

    patch: no
    changes: no
