[[agents]]
id = "test agent"
name = "Holo Tester"
key_file = "holo_tester.key"

[[dnas]]
id = "app spec rust"
file = "example-config/app_spec.hcpkg"
hash = "Qm328wyq38924y"

[[instances]]
id = "app spec instance"
dna = "app spec rust"
agent = "test agent"
[instances.logger]
type = "simple"
file = "app_spec.log"
[instances.storage]
type = "file"
path = "example-config/tmp-storage"


[[interfaces]]
id = "websocket interface"
[interfaces.driver]
type = "websocket"
port = 3000
[[interfaces.instances]]
id = "app spec instance"

# [[interfaces]]
# id = "http interface"
# [interfaces.driver]
# type = "http"
# port = 8008
# [[interfaces.instances]]
# id = "app spec instance"
