[[agents]]
id = "test agent"
name = "Holo Tester"
key_file = "holo_tester.key"

[[dnas]]
id = "app spec rust"
file = "example-config/app-spec-rust.hcpkg"
hash = "Qm328wyq38924y"

[[instances]]
id = "app spec instance"
dna = "app spec rust"
agent = "test agent"
[instances.logger]
type = "simple"
file = "app_spec.log"
[instances.storage]
type = "file"
path = "example-config/tmp-storage"


[[interfaces]]
type = "websocket"
port = 8888
[[interfaces.instances]]
id = "app spec instance"
