[package]
name = "holochain_dna_c_binding"
version = "0.0.18-alpha1"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]

[lib]
name = "holochain_dna_c_binding"
crate-type = ["staticlib"]

[dependencies]
holochain_core_types = { path = "../core_types" }
lib3h_persistence_api = "=0.0.1-alpha2"
