[package]
name = "holochain_dna_c_binding"
version = "0.1.0"
authors = ["neonphog <neonphog@gmail.com>"]

[lib]
name = "holochain_dna_c_binding"
crate-type = ["staticlib"]

[dependencies]
holochain_dna = { path = "../dna" }
holochain_core_types = { path = "../core_types" }
