[package]
name = "test_utils"
version = "0.0.4-alpha"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
edition = "2018"

[dependencies]
holochain_net = { path = "../net" }
holochain_core = { path = "../core" }
holochain_conductor_api = { path = "../conductor_api" }
holochain_cas_implementations = { path = "../cas_implementations" }
holochain_core_types = { path = "../core_types" }
holochain_dpki = { path = "../hc_dpki" }
holochain_sodium = { path = "../sodium" }
wabt = "0.7.2"
tempfile = "3"
serde_json = { version = "1.0", features = ["preserve_order"] }
lazy_static = "1.2"
jsonrpc-ws-server = { git = "https://github.com/paritytech/jsonrpc" }
base64 = "0.10"