[package]
name = "test_utils"
version = "0.0.1"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]

[dependencies]
holochain_dna = { path = "../dna" }
holochain_core = { path = "../core" }
holochain_core_api = { path = "../core_api" }
holochain_agent = { path = "../agent" }
holochain_cas_implementations = { path = "../cas_implementations" }
holochain_core_types = { path = "../core_types" }
wabt = "0.4"
tempfile = "3"
