[package]
name = "test_utils"
version = "0.0.3"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]

[dependencies]
holochain_net = { path = "../net" }
holochain_core = { path = "../core" }
holochain_conductor_api = { path = "../conductor_api" }
holochain_cas_implementations = { path = "../cas_implementations" }
holochain_core_types = { path = "../core_types" }
wabt = "0.7.2"
tempfile = "3"
serde_json = { version = "1.0", features = ["preserve_order"] }
