[package]
name = "holochain_core_api_c_binding"
version = "0.0.3"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]

[lib]
name = "holochain_core_api_c_binding"
crate-type = ["staticlib"]


[dependencies]
holochain_core = { path = "../core" }
holochain_conductor_api = { path = "../conductor_api" }
holochain_net = { path = "../net" }
holochain_cas_implementations = { path = "../cas_implementations" }
holochain_core_types = { path = "../core_types" }
directories="1.0.2"
