[package]
name = "holochain_core_types"
version = "0.0.1"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = { version = "1.0", features = ["preserve_order"] }
multihash = "0.8.0"
futures-preview = "0.2.2"
rust-base58 = "0.0.4"
snowflake = "1.2"
bitflags = "1.0"
objekt="0.1.1"
holochain_core_types_derive = { path = "../core_types_derive" }
uuid = { version = "0.7", features = ["v4"] }

[dev-dependencies]
test_utils = { path = "../test_utils"}
holochain_core = { path = "../core"}
