[package]
name = "holochain_stress"
version = "0.0.37-alpha12"
description = "holochain stress tests"
license = "GPL-3.0-only"
homepage = "https://github.com/holochain/holochain-rust"
documentation = "https://github.com/holochain/holochain-rust"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
edition = "2018"

[dependencies]
native-tls = "=0.2.2"

[features]
vendored = ["native-tls/vendored"]
default = [ "vendored" ]
