version: 2.0

jobs:
  checkout_code:
    docker:
      - image: circleci/buildpack-deps:stable-curl
    working_directory: ~/holochain
    steps:
      - checkout
      - save_cache:
        key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
        paths:
          - ~/holochain

  cargo_dependencies:
    docker:
      - image: circleci/buildpack-deps:stable-curl
    working_directory: ~/holochain
    steps:
      - restore_cache:
        key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
        key: v1-bundle-{{ checksum "Cargo.lock" }}
      - run: make install_rustup
      - command: |
         echo 'export PATH=$HOME/.cargo/bin:$PATH' >> $BASH_ENV
         source /home/circleci/.bashrc
      - run: make build
      - save_cache:
        key: v1-bundle-{{ checksum "Cargo.lock" }}
        paths:
          - $HOME/.cargo
          - ~/holochain/target

workflows:
  version: 2
  build-and-test:
    jobs:
      - checkout_code
      - cargo_dependencies:
        requires:
          - checkout_code
