version: 2
jobs:
  build:
    docker:
      - image: holochain/holochain-rust:circle
    steps:
      - restore_cache:
          keys:
            - nix

      - checkout

      - run:
          name: add nix unstable
          command: nix-channel --add https://nixos.org/channels/nixpkgs-unstable

      - run:
          name: update nix channel
          command: nix-channel --update

      - run:
          name: fmt check
          command: nix-shell --run hc-fmt-check

      - save_cache:
          key: nix
          paths:
            - "/nix"
