version: 2
jobs:
  build:
    docker:
      - image: holochain/holochain-rust:circle
    steps:
      - checkout


      - restore_cache:
          keys:
            # todo: keys for each target
            - v2-rust-{{ checksum "Cargo.toml" }}

      - run:
          name: fmt check
          command: nix-shell --run hc-fmt-check

      - restore_cache:
          keys:
            - v2-wasm-{{ checksum "core/src/nucleus/actions/wasm-test/Cargo.toml" }}
      - run:
          name: build wasm
          command: nix-shell --run hc-wasm-build
      - save_cache:
          key: v2-wasm-{{ checksum "core/src/nucleus/actions/wasm-test/Cargo.toml" }}
          paths:
            - "./core/src/nucleus/actions/wasm-test/target"
            - "./core/src/nucleus/actions/wasm-test/.cargo"

      - run:
          name: code coverage tests and push
          command: nix-shell --run hc-tarpaulin

      - run:
          name: install cmd
          command: nix-shell --run hc-install-cmd

      # test the node container build
      # todo - this cache doesn't stop recompilation of rust on node container
      - restore_cache:
          keys:
            - v1-nodejs_container-{{ checksum "nodejs_container/package.json" }}-{{ checksum "nodejs_container/publish.js" }}-{{ checksum "nodejs_container/yarn.lock" }}-{{ checksum "nodejs_container/native/Cargo.toml" }}
      - run:
          name: install node container
          command: nix-shell --run hc-install-node-container
      - save_cache:
          key: v1-nodejs_container-{{ checksum "nodejs_container/package.json" }}-{{ checksum "nodejs_container/publish.js" }}-{{ checksum "nodejs_container/yarn.lock" }}-{{ checksum "nodejs_container/native/Cargo.toml" }}
          paths:
            - "./nodejs_container/native/target"
            - "./nodejs_container/node_modules"
            - "./nodejs_container/native/Cargo.lock"

      - run:
          name: app spec tests
          command: nix-shell --run hc-test-app-spec

      - save_cache:
          key: v2-rust-{{ checksum "Cargo.toml" }}
          paths:
            - "~/.cargo"
            - "./target"
            - "./app_spec/zomes/blog/code/target"
            - "./app_spec/zomes/summer/code/target"
            - "./container_api/wasm-test/target"
            - "./core/src/nucleus/ribosome/target"
            - "./core/src/nucleus/wasm-test/target"
            - "./wasm_utils/wasm-test/integration-test/target"
            - "./hdk-rust/wasm-test/target"
            - "./test_utils/target"
