version: 2
jobs:
  build:
    docker:
      - image: holochain/holochain-rust:circle
    steps:
      - restore_cache:
          keys:
            - nix

      - checkout

      - run:
          name: cat shell.nix
          command: cat shell.nix

      - run:
          name: fmt check
          command: nix-shell --run hc-fmt-check

      - run:
          name: wasm build and test
          command: nix-shell --run "hc-wasm-build && hc-test"

      - save_cache:
          key: nix
          paths:
            - "/nix"
