version: 2.0

jobs:
  checkout_code:
    docker:
      - image: circleci/buildpack-deps:stable-curl
    working_directory: ~/holochain
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/holochain
  build:
    docker:
      - image: circleci/buildpack-deps:stable-curl
    working_directory: ~/holochain
    steps:
      - checkout
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-bundle-{{ checksum "Cargo.lock" }}
      - run: ls -la
      - run: df -h
      - run: make install_rustup
      - run: echo 'export PATH=$HOME/.cargo/bin:$PATH' >> $BASH_ENV
      - run: source /home/circleci/.bashrc
      - save_cache:
          key: v1-bundle-{{ checksum "Cargo.lock" }}
          paths:
            - $HOME/.cargo
            - ~/holochain/target

workflows:
  version: 2.0
  test:
    jobs:
      - checkout_code
      - build:
        requires:
          - checkout_code
      # - cargo_dependencies:
      #     requires:
      #       - checkout_code
