version: 2
jobs:
  build:
    docker:
      - image: holochain/holochain-rust:circle
    steps:
      - checkout

      - run:
          name: fmt check
          command: nix-shell --run hc-fmt-check

      # hdk test
      - restore_cache:
         keys:
          - hdk-v1-{{ checksum "hdk-rust/Cargo.toml" }}-{{ checksum "hdk-rust/wasm-test/Cargo.toml" }}
      - run:
         name: test hdk
         command: nix-shell --run hc-test-hdk
      - save_cache:
         key: hdk-v1-{{ checksum "hdk-rust/Cargo.toml" }}-{{ checksum "hdk-rust/wasm-test/Cargo.toml" }}
         paths:
          - hdk-rust/target
          - hdk-rust/wasm-test/target

      # wasm-utils test
      - restore_cache:
         keys:
          - wasm-utils-v1-{{ checksum "wasm_utils/Cargo.toml" }}-{{ checksum "wasm_utils/wasm-test/integration-test/Cargo.toml" }}
      - run:
         name: test wasm utils
         command: nix-shell --run hc-test-wasm-utils
      - save_cache:
         key: wasm-utils-v1-{{ checksum "wasm_utils/Cargo.toml" }}-{{ checksum "wasm_utils/wasm-test/integration-test/Cargo.toml" }}
         paths:
          - wasm_utils/target
          - wasm_utils/wasm-test/integration-test/target

      # container api test
      - restore_cache:
         keys:
          - wasm-utils-v1-{{ checksum "container_api/Cargo.toml" }}-{{ checksum "container_api/wasm-test/Cargo.toml" }}
      - run:
         name: test container api
         command: nix-shell --run hc-test-container-api
      - save_cache:
         key: wasm-utils-v1-{{ checksum "container_api/Cargo.toml" }}-{{ checksum "container_api/wasm-test/Cargo.toml" }}
         paths:
          - container_api/target
          - container_api/wasm-test/target

      # core test
      - restore_cache:
         keys:
          - wasm-utils-v1-{{ checksum "core/Cargo.toml" }}-{{ checksum "core/src/nucleus/actions/wasm-test/Cargo.toml" }}
      - run:
         name: test core
         command: nix-shell --run hc-test-core
      - save_cache:
         key: wasm-utils-v1-{{ checksum "core/Cargo.toml" }}-{{ checksum "core/src/nucleus/actions/wasm-test/Cargo.toml" }}
         paths:
          - core/target
          - core/src/nucleus/actions/wasm-test/target


      - run:
          name: install cmd
          command: nix-shell --run hc-install-cmd

      # test the node container build
      # todo - this cache doesn't stop recompilation of rust on node container
      - restore_cache:
          keys:
            - v1-nodejs_container-{{ checksum "nodejs_container/package.json" }}-{{ checksum "nodejs_container/publish.js" }}-{{ checksum "nodejs_container/yarn.lock" }}-{{ checksum "nodejs_container/native/Cargo.toml" }}
      - run:
          name: install node container
          command: nix-shell --run hc-install-node-container
      - save_cache:
          key: v1-nodejs_container-{{ checksum "nodejs_container/package.json" }}-{{ checksum "nodejs_container/publish.js" }}-{{ checksum "nodejs_container/yarn.lock" }}-{{ checksum "nodejs_container/native/Cargo.toml" }}
          paths:
            - "./nodejs_container/native/target"
            - "./nodejs_container/node_modules"
            - "./nodejs_container/native/Cargo.lock"

      - run:
          name: app spec tests
          command: nix-shell --run hc-test-app-spec
