[package]
name = "test-bridge-caller"
version = "0.0.43-alpha2"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]

[lib]
crate-type = ["cdylib"]

[profile.release]
panic = "abort"

[workspace]
members = []

[dependencies]
serde = "=1.0.100"
serde_json = { version = "=1.0.47", features = ["preserve_order"] }
hdk = { path = "../../hdk" }
serde_derive = "=1.0.100"
holochain_json_derive = "=0.0.20"
holochain_persistence_api = "=0.0.15"
