[package]
name = "hc_dna_c_binding"
version = "0.1.0"
authors = ["neonphog <neonphog@gmail.com>"]

[lib]
name = "hc_dna_c_binding"
crate-type = ["staticlib"]

[dependencies]
hc_dna = { path = "../hc_dna" }
