[package]
name = "round-trip"
version = "0.0.1"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]

[lib]
crate-type = ["cdylib"]

[profile.release]
panic = "abort"
lto = true
opt-level = 'z'

[workspace]
members = []

[dependencies]
<<<<<<< HEAD
serde = "1.0"
serde_derive = "1.0"
serde_json = { version = "1.0", features = ["preserve_order"] }
=======
serde="1"
serde_derive="1"
>>>>>>> da8059ec89cfc40bb22f543dba06c32e7fd60ba6
holochain_wasm_utils = { path = "../../../wasm_utils"}
