[package]
name = "hdk-proc-macros"
version = "0.0.10-alpha2"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.15.29", features = ["full"]}
quote = "0.6.3"

hdk = { path = "../hdk-rust" }