[package]
name = "holochain_cas_implementations"
version = "0.1.0"
authors = ["Holochain Core Dev Team <dev.support@holo.host>"]

[dependencies]
serde="1"
serde_derive="1"
serde_json="1"
multihash = "0.8.0"
