[package]
name = "hc_core_api"
version = "0.1.0"
authors = ["Eric Harris-Braun <eric@harris-braun.com>"]

[dependencies]
hc_core = { path = "../hc_core" }
hc_dna = { path = "../hc_dna" }
hc_agent = { path = "../hc_agent" }
