[package]
name = "code"
version = "0.0.22-alpha1"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]

[dependencies]
serde = "=1.0.89"
serde_json = { version = "=1.0.39", features = ["preserve_order"] }
hdk = { path = "../../../../hdk-rust" }
hdk-proc-macros = { path = "../../../../hdk-proc-macros" }

holochain_json_derive = { git = "https://github.com/holochain/holochain-serialization", branch = "2019-06-27-bump-nightly" }
serde_derive = "=1.0.89"
boolinator = "=2.4.0"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
