[package]
name = "holochain_test_bin"
version = "0.0.1"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]

[dependencies]
holochain_core = { path = "../core" }
holochain_dna = { path = "../dna" }
holochain_core_api = { path = "../core_api" }
holochain_cas_implementations = {path="../cas_implementations"}
holochain_core_types = { path = "../core_types" }
tempfile = "3"
