[package]
name = "hc_core"
version = "0.1.0"
authors = ["Nicolas Luck <nicolas@lucksus.org>"]

[dependencies]
hc_dna = { path = "../hc_dna" }
hc_agent = { path = "../hc_agent" }
chrono = "0.4"
wasmi = { git = "https://github.com/paritytech/wasmi.git"}
wabt = "0.2.0"
snowflake = "1.2"
