[package]
name = "test-proc-macro"
version = "0.0.10-alpha2"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]

[lib]
crate-type = ["cdylib"]

[profile.release]
panic = "abort"

[workspace]
members = []

[dependencies]
hdk-proc-macros = { path = ".." }
hdk = { path = "../../hdk-rust" }
