[package]
name = "holochain"
version = "0.0.41-alpha4"
description = "holochain"
license = "GPL-3.0-only"
homepage = "https://github.com/holochain/holochain-rust"
documentation = "https://github.com/holochain/holochain-rust"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]

[dependencies]
holochain_core_types = { version = "=0.0.41-alpha4", path = "../core_types" }
holochain_conductor_lib = { version = "=0.0.41-alpha4", path = "../conductor_lib" }
lib3h_sodium = { version = "=0.0.26", git = "https://github.com/holochain/lib3h", branch = "tracing-0.0.6" }
holochain_common = { version = "=0.0.41-alpha4", path = "../common" }
holochain_locksmith = { version = "=0.0.41-alpha4", path = "../locksmith" }
holochain_tracing = "=0.0.6"
holochain_tracing_macros = "=0.0.3"
structopt = "=0.2.15"
tiny_http = "=0.6.2"
ws = "=0.8.0"
log = "=0.4.8"

[target.'cfg(unix)'.dependencies]
signal-hook = "=0.1.10"
