[package]
name = "holochain"
version = "0.0.33-alpha5"
description = "holochain"
license = "Apache-2.0"
homepage = "https://github.com/holochain/holochain-rust"
documentation = "https://github.com/holochain/holochain-rust"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]

[dependencies]
holochain_core_types = { version = "=0.0.33-alpha5", path = "../core_types" }
holochain_conductor_lib = { version = "=0.0.33-alpha5", path = "../conductor_lib" }
lib3h_sodium = "=0.0.19"
holochain_common = { version = "=0.0.33-alpha5", path = "../common" }
structopt = "=0.2.15"
tiny_http = "=0.6.2"
ws = "=0.8.0"
[target.'cfg(unix)'.dependencies]
signal-hook = "=0.1.10"
