[package]
name = "holochain"
version = "0.0.33-alpha5"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]

[dependencies]
holochain_core_types = { path = "../core_types" }
holochain_conductor_lib = { path = "../conductor_lib" }
lib3h_sodium = { path = "/home/neonphog/projects/lib3h/crates/sodium" }
holochain_common = { path = "../../common" }
structopt = "=0.2.15"
tiny_http = "=0.6.2"
ws = "=0.8.0"
[target.'cfg(unix)'.dependencies]
signal-hook = "=0.1.10"
