[package]
name = "holochain_common"
description = "holochain core commons"
license = "GPL-3.0-only"
homepage = "https://github.com/holochain/holochain-rust"
documentation = "https://github.com/holochain/holochain-rust"
version = "0.0.42-alpha5"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
edition = "2018"

[dependencies]
directories = "=1.0.2"
holochain_json_api = "=0.0.17"
holochain_json_derive = "=0.0.17"
serde_derive = "=1.0.89"
serde = "=1.0.89"
serde_json = "=1.0.39"
