[package]
name = "holochain_common"
description = "holochain core commons"
license = "Apache-2.0"
homepage = "https://github.com/holochain/holochain-rust"
documentation = "https://github.com/holochain/holochain-rust"
version = "0.0.34-alpha1"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
edition = "2018"

[dependencies]
directories = "=1.0.2"
