[package]
name = "hc_test_bin"
version = "0.1.0"
authors = ["neonphog <neonphog@gmail.com>"]

[dependencies]
hc_core = { path = "../hc_core" }
hc_dna = { path = "../hc_dna" }
hc_agent = { path = "../hc_agent" }
hc_core_api = { path = "../hc_core_api" }
