[package]
name = "sim2h_server"
version = "0.0.41-alpha4"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
edition = "2018"
description = "A simulation of lib3h - server executable"
keywords = ["holochain", "holo", "p2p", "network", "simulation"]
categories = ["network-programming"]
license = "GPL-3.0-only"
readme = "README.md"
documentation = "https://github.com/holochain/sim2h"
repository = "https://github.com/holochain/sim2h"

[dependencies]
sim2h = { version = "=0.0.41-alpha4", path = "../sim2h" }
detach = "=0.0.19"
lib3h = "=0.0.25"
lib3h_crypto_api = "=0.0.25"
lib3h_protocol = "=0.0.25"
lib3h_sodium = "=0.0.25"
log = "0.4.8"
env_logger = "0.7.0"
structopt = "=0.2.15"
url2 = "=0.0.4"
in_stream = { version = "=0.0.41-alpha4", path = "../in_stream" }
dns-lookup = "1.0.1"
hcid = "=0.0.6"
base64 = "=0.10.1"
serde = "=1.0.89"
serde_derive = "=1.0.89"
serde_json = { version = "=1.0.39", features = ["preserve_order"] }
