[package]
name = "nucleus-actions-tests"
version = "0.0.21-alpha1"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]

[lib]
crate-type = ["cdylib"]

[profile.release]
panic = "abort"

[workspace]
members = []

[dependencies]
hdk = { path = "../../../../../hdk-rust" }
holochain_json_derive = { git = "https://github.com/holochain/holochain-serialization", branch = "2019-06-27-bump-nightly" }
serde = "=1.0.89"
serde_json = { version = "=1.0.39", features = ["preserve_order"] }
serde_derive = "=1.0.89"
boolinator = "=2.4.0"
