[package]
name = "simple"
version = "0.1.0"
authors = ["Ashanti Mutinta <Ashantimutinta@gmail.com>"]
edition = "2018"

[dependencies]
serde = "=1.0.89"
serde_json = { version = "=1.0.39", features = ["preserve_order"] }
serde_derive = "=1.0.89"
hdk = { path = "../../../../hdk-rust" }
holochain_core_types_derive = { path = "../../../../core_types_derive" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
