[package]
name = "holochain_net"
version = "0.0.1"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]

[dependencies]
base64 = "0.9.3"
failure = "0.1.1"
holochain_core_types = { path = "../core_types" }
holochain_net_connection = { path = "../net_connection" }
holochain_net_ipc = { path = "../net_ipc" }
serde_json = { version = "1", features = ["preserve_order"] }
